### ISSUE TITLE
Error 404 displayed after payment completion

### ISSUE THREAD

**Issue by bosunjohnson** [PaystackHQ/Paystack-gateway-for-Prestashop-1.7#1]
Thanks for this plugin but.
After the user has entered card details and clicked pay, a prestashop error 404 page appears.
The plugin should be made to display a transaction successful page after the payment is made or transaction declined if payment is not succesful.

**Comment by seyi-adetunji** [comment]
Hi, 
   I am experiencing the same issues with PrestaShop 1.7 Error 500 and payment is deducted twice if the browser is refreshed. Can you advise on this as soon as possible?

**Comment by steveamaza** [comment]
Hi @seyi-adetunji please check your server error logs for the error shown and then paste in a separate issue so we can debug properly

**Comment by seyi-adetunji** [comment]
Please, also note that there is no callback URL for the plugin.
