### ISSUE TITLE
Error showing when install and configure

### ISSUE THREAD

**Issue by radix21** [PaystackHQ/Paystack-gateway-for-Prestashop-1.7#3]
Notice:  In line 150 at file /Applications/XAMPP/xamppfiles/htdocs/inval-ecommerce/vendor/prestashop/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()&#039;d code
[8] Undefined index: form

Prestashop: V. 1.7.2

**Comment by steveamaza** [comment]
Hello @radix21,

Can you provide more information regarding this error? It doesn't seem to come from the Paystack plugin
