### ISSUE TITLE
Paystack Payment Options not added to "Payment Checkouts"

### ISSUE THREAD

**Issue by erisanolasheni** [PaystackHQ/Paystack-gateway-for-Prestashop-1.7#8]
5Hello, I just installed the "Prestashop 1.7 Paystack" module on my localhost prestashop. Withh the test keys added to the configuration. But the "Paystack Payment" is not included int the checkout payments options, which is make the module not active, see image below.

![screenshot-2018-1-15 drug bulk](https://user-images.githubusercontent.com/6621375/34947892-cdcc7d44-fa0b-11e7-9eee-e297324d0b08.png)

**Comment by steveamaza** [comment]
Hi @Software202, let me do some testing on this end. In the meantime, let me have a link to your site.

**Comment by erebun** [comment]
Hi, I just installed Paystack to my Prestashop 1.7 but it is not showing at the payment option page, how do I resolve this

**Comment by steveamaza** [comment]
@erebun please provide a link to your site

**Comment by erebun** [comment]
http://mespirator.com

I plan to launch the site by end of this month.

**Comment by steveamaza** [comment]
Countries haven't been set on your PrestaShop store to begin with. Please add countries so I can checkout to the payment options bit
![image](https://user-images.githubusercontent.com/15840315/57983042-27c40280-7a45-11e9-8566-982fa7708611.png)

**Comment by erebun** [comment]
Thank you I have seen where the problem came from based on your reply.

**Comment by taiwoobe** [comment]
Hello,

I am having the same issue just that mine is on the 1.6 Version. Here is a link to the site - https://shop4younow.com.ng/

**Comment by opeolade** [comment]
Paystack Payment Options added to "Payment Checkouts" when currency is on naira, but
Paystack Payment Options not added to "Payment Checkouts" when currency is on $
